# permissions for end users to view xfirewalls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xfirewall-viewer-role
rules:
- apiGroups:
  - cluster.www.x-cellent.com
  resources:
  - xfirewalls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.www.x-cellent.com
  resources:
  - xfirewalls/status
  verbs:
  - get
